"""
CI helpers for SbtDeskTran releases.

Typical CI flow:
  python ci_release.py set-version v2026.07.07.8
  python -m PyInstaller ...
  python ci_release.py assets v2026.07.07.8
  python ci_release.py release v2026.07.07.8
"""
import argparse
import datetime as dt
import os
import pathlib
import re
import shutil
import subprocess
import sys
import zipfile


APP_EXE_NAME = "SbtDeskTran.exe"
DIST_DIR = pathlib.Path("dist")
VERSION_FILE = pathlib.Path("version.py")
VERSION_CHANGES = pathlib.Path("version_changes.txt")
SECTION_SEPARATOR_LEN = 65
SEP = "-" * SECTION_SEPARATOR_LEN


# ── Version helpers ─────────────────────────────────────────────

def normalize_version(value: str) -> str:
    raw = (value or "").strip()
    match = re.search(r"\bv?(\d+(?:\.\d+)+)\b", raw)
    if not match:
        raise SystemExit(
            "Release version must contain a numeric tag like v2026.07.07.8"
        )
    return match.group(1)


def version_arg(value: str = "") -> str:
    return normalize_version(
        value or os.environ.get("RELEASE_VERSION") or os.environ.get("GITHUB_REF_NAME", "")
    )


def _ver_tuple(v: str) -> tuple:
    return tuple(int(p) for p in re.findall(r"\d+", v))


def set_version(version: str) -> None:
    VERSION_FILE.write_text(
        '# Auto-generated by CI/CD - do not edit manually\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


# ── Git helpers ─────────────────────────────────────────────────

def run_git(*args: str, check: bool = True) -> str:
    result = subprocess.run(
        ["git", *args], check=False,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    stdout = result.stdout.decode("utf-8", errors="replace") if result.stdout else ""
    stderr = result.stderr.decode("utf-8", errors="replace") if result.stderr else ""
    if check and result.returncode != 0:
        raise SystemExit(stderr.strip() or f"git {' '.join(args)} failed")
    return stdout.strip()


def git_success(*args: str) -> bool:
    return subprocess.run(["git", *args], check=False).returncode == 0


def last_release_tag() -> str:
    """Return the most recent tag matching v*, falling back to the root commit."""
    tag = run_git("describe", "--tags", "--abbrev=0", "--match", "v*", check=False)
    return tag or run_git("rev-list", "--max-parents=0", "HEAD")


def change_summary(base_ref: str) -> str:
    commits = run_git("log", "--oneline", f"{base_ref}..HEAD", check=False).splitlines()
    files = run_git("diff", "--name-only", f"{base_ref}..HEAD", check=False).splitlines()
    lines = ["Commits:"]
    lines.extend(f"- {line}" for line in commits[:30])
    if not commits:
        lines.append("- No commit summary available")
    lines.append("")
    lines.append("Changed files:")
    lines.extend(f"- {line}" for line in files[:50])
    if not files:
        lines.append("- No changed file summary available")
    return "\n".join(lines)


def git_configure():
    run_git("config", "user.email", "github-actions[bot]@users.noreply.github.com")
    run_git("config", "user.name", "github-actions[bot]")


# ── version_changes.txt helpers ─────────────────────────────────

def _read_changes() -> str:
    return VERSION_CHANGES.read_text(encoding="utf-8") if VERSION_CHANGES.exists() else ""


def _write_changes(text: str):
    VERSION_CHANGES.write_text(text, encoding="utf-8")


def _parse_last_released(text: str) -> str:
    """Read 'Last released: v...' from the file header."""
    for line in text.splitlines():
        m = re.match(r"Last released:\s*(.+)", line)
        if m:
            return m.group(1).strip()
    return ""


def _set_last_released(text: str, version: str) -> str:
    line = f"Last released: v{version}"
    if re.search(r"(?m)^Last released:.*$", text):
        return re.sub(r"(?m)^Last released:.*$", line, text)

    lines = text.splitlines()
    insert_at = 0
    if lines and lines[0].strip():
        insert_at = 1
        while insert_at < len(lines) and lines[insert_at].strip() == "":
            insert_at += 1
    lines.insert(insert_at, "")
    lines.insert(insert_at + 1, line)
    return "\n".join(lines)


def _find_section_versions(text: str) -> list[tuple[tuple, int, int]]:
    """
    Find all section headers between --- separators.
    Returns list of (version_tuple, title_line_index, sep_after_title_index).
    """
    lines = text.splitlines()
    result = []
    i = 0
    while i < len(lines):
        if _is_section_separator(lines[i]):
            # Next line might be a version title
            if i + 1 < len(lines):
                m = re.match(r"v(\d+(?:\.\d+)+)", lines[i + 1].strip())
                if m:
                    # Find closing ---
                    close = i + 2
                    while close < len(lines) and not _is_section_separator(lines[close]):
                        close += 1
                    result.append((_ver_tuple(m.group(1)), i + 1, close))
                    i = close + 1
                    continue
        i += 1
    return result


def _is_section_separator(line: str) -> bool:
    stripped = line.strip()
    return len(stripped) >= 10 and set(stripped) == {"-"}


def _extract_section_body(text: str, title_idx: int, close_idx: int) -> str:
    """Extract the body of a section (lines after closing --- until next --- or EOF)."""
    lines = text.splitlines()
    start = close_idx + 1
    body = []
    for i in range(start, len(lines)):
        if _is_section_separator(lines[i]):
            break
        body.append(lines[i])
    return "\n".join(body).strip()


def _build_section(version: str, body: str) -> str:
    return f"\n\n{SEP}\nv{version} — Auto-generated\n{SEP}\n\n{body}\n\n"


def _insert_after_last_released(text: str, section: str) -> str:
    lines = text.splitlines()
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("Last released:"):
            insert_at = i + 1
            while insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            break
    lines.insert(insert_at, section.strip())
    return "\n".join(lines)


def prepare_version_changes(version: str) -> tuple[str, bool]:
    today = dt.date.today().isoformat()
    original = _read_changes()
    text = original or "SbtDeskTran version changes\n"
    date_tuple = _ver_tuple(version)[:3]

    matched = None
    for vt, title_idx, close_idx in _find_section_versions(text):
        if vt[:3] == date_tuple:
            matched = (title_idx, close_idx)
            break

    if matched:
        title_idx, close_idx = matched
        notes = _extract_section_body(text, title_idx, close_idx)
    else:
        base = last_release_tag()
        summary = change_summary(base)
        section = _build_section(version, summary)
        text = _insert_after_last_released(_set_last_released(text, version), section)
        notes = f"Auto-generated release notes for v{version} ({today}).\n\n{summary}"

    text = _set_last_released(text, version)
    updated = text != original
    if updated:
        _write_changes(text.rstrip() + "\n")
    return notes, updated


# ── Commands ────────────────────────────────────────────────────

def create_assets(version: str) -> None:
    prepare_version_changes(version)
    DIST_DIR.mkdir(exist_ok=True)
    exe_path = DIST_DIR / APP_EXE_NAME
    if not exe_path.exists():
        raise SystemExit(f"Missing build output: {exe_path}")

    for stale in ("latest.json", "release_notes.txt"):
        p = DIST_DIR / stale
        if p.exists():
            p.unlink()

    zip_path = DIST_DIR / f"SbtDeskTran-{version}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.write(exe_path, APP_EXE_NAME)

    changes_out = DIST_DIR / "version_changes.txt"
    if VERSION_CHANGES.exists():
        shutil.copyfile(VERSION_CHANGES, changes_out)
    else:
        changes_out.write_text("SbtDeskTran version changes\n", encoding="utf-8")


def do_release(version: str, *, push_tag: bool = False, draft: bool = False) -> None:
    """
    Prepare release notes and create a GitHub release.

    1. Read version_changes.txt.
    2. Look for a manual section whose version matches the date part of
       the current build version (e.g. section ``v2026.07.08`` matches
       build ``2026.07.08.15``).
    3. If found → use that section as the release body.
    4. If not  → auto-generate a section from git diff since the last
       release tag, append it to the file, commit (with ``[skip ci]``),
       push.
    5. Create the GitHub release.
    """
    tag = f"v{version}"
    notes, _ = prepare_version_changes(version)

    if not git_success("diff", "--quiet", "--", VERSION_CHANGES.as_posix()):
        git_configure()
        run_git("add", VERSION_CHANGES.as_posix())
        run_git("commit", "-m", f"Update version changes for v{version} [skip ci]")
        run_git("push")

    if push_tag:
        run_git("tag", tag)
        run_git("push", "origin", tag)

    zip_path = DIST_DIR / f"SbtDeskTran-{version}.zip"
    cmd = [
        "gh", "release", "create", tag,
        "--title", f"{tag}",
        "--notes", notes,
    ]
    if draft:
        cmd.append("--draft")
    if zip_path.exists():
        cmd.append(str(zip_path))
    changes_asset = DIST_DIR / "version_changes.txt"
    if changes_asset.exists():
        cmd.append(str(changes_asset))

    result = subprocess.run(cmd, capture_output=True)
    stdout = result.stdout.decode("utf-8", errors="replace") if result.stdout else ""
    stderr = result.stderr.decode("utf-8", errors="replace") if result.stderr else ""
    if result.returncode != 0:
        raise SystemExit(f"gh release create failed:\n{stderr.strip()}")
    print(stdout.strip())
    print(f"Release {tag} created successfully.")


# ── CLI ─────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    set_version_parser = subparsers.add_parser("set-version")
    set_version_parser.add_argument("version", nargs="?")

    assets_parser = subparsers.add_parser("assets")
    assets_parser.add_argument("version", nargs="?")

    release_parser = subparsers.add_parser("release")
    release_parser.add_argument("version", nargs="?")
    release_parser.add_argument("--push-tag", action="store_true",
        help="Create and push the Git tag before creating the release")
    release_parser.add_argument("--draft", action="store_true",
        help="Create the release as a draft")

    args = parser.parse_args()

    if args.command == "set-version":
        set_version(version_arg(args.version))
    elif args.command == "assets":
        create_assets(version_arg(args.version))
    elif args.command == "release":
        do_release(
            version_arg(args.version),
            push_tag=args.push_tag,
            draft=args.draft,
        )
    else:
        sys.exit(2)


if __name__ == "__main__":
    main()
